insert into ACADEMIC values (100, 100, 'Kornreich', 'Jeroen', 'J D', 'AProf');
insert into ACADEMIC values (101, 100, 'Yee', 'Mark', 'M D', 'Dr');
insert into ACADEMIC values (102, 100, 'Fernandes', 'Russell', 'R T J', 'Mr');
insert into ACADEMIC values (103, 100, 'Cohen', 'Richard', 'R R A', 'AProf');
insert into ACADEMIC values (104, 100, 'Polemitis', 'Joe', 'J L', 'Miss');
insert into ACADEMIC values (105, 100, 'Brower', 'Tony', 'T B', 'AProf');
insert into ACADEMIC values (106, 100, 'Royce', 'Mel', 'M P', 'Prof');
insert into ACADEMIC values (107, 100, 'Christine', 'Leonardo', 'L T P', 'Mr');
insert into ACADEMIC values (108, 100, 'Brandon', 'Chuck', 'C A', 'Dr');
insert into ACADEMIC values (109, 101, 'Gustafsson', 'Hakan', 'H O Y', 'Dr');
insert into ACADEMIC values (111, 132, 'Barton', 'Michel', 'M G K', 'Prof');
insert into ACADEMIC values (113, 101, 'Sadhal', 'Sharanya', 'S B', 'Dr');
insert into ACADEMIC values (114, 101, 'Morley', 'Chris', 'C M T', 'Ms');
insert into ACADEMIC values (115, 145, 'Garton', 'Graham', 'G A S M', 'Dr');
insert into ACADEMIC values (116, 147, 'Nair', 'Marc', 'M P', 'Mr');
insert into ACADEMIC values (117, 101, 'Baliga', 'Lance', 'L G C', 'Dr');
insert into ACADEMIC values (118, 145, 'Rickert', 'Hannu', 'H X', 'Dr');
insert into ACADEMIC values (119, 102, 'Lamkin', 'Bas', 'B M', 'Dr');
insert into ACADEMIC values (120, 102, 'Tang', 'Greg', 'G J', 'Mr');
insert into ACADEMIC values (121, 102, 'Skelton', 'Robert', 'R R S', 'Mr');
insert into ACADEMIC values (122, 142, 'Harris', 'Mark', 'M J L', 'Mr');
insert into ACADEMIC values (123, 102, 'Wyld', 'Mitchell', 'M S', 'Dr');
insert into ACADEMIC values (124, 102, 'Haenssgen', 'Francis', 'F A', 'Mr');
insert into ACADEMIC values (125, 102, 'Ahlberg', 'Grosek', 'G F', 'Ms');
insert into ACADEMIC values (126, 102, 'Bodoh', 'Anne', 'A S', 'Dr');
insert into ACADEMIC values (127, 102, 'Hathaway', 'Walley', 'W J', 'Dr');
insert into ACADEMIC values (128, 102, 'Silvermane', 'Ajay', 'A A N', 'Dr');
insert into ACADEMIC values (129, 102, 'Hopkins', 'Sheldon', 'S T', 'AProf');
insert into ACADEMIC values (130, 102, 'Correll', 'Tim', 'T N K', 'Dr');
insert into ACADEMIC values (131, 102, 'Ruschak', 'Robert', 'R H K', 'Mr');
insert into ACADEMIC values (132, 103, 'Bataille', 'Michael', 'M J', 'Prof');
insert into ACADEMIC values (133, 103, 'Reichelt', 'Lee', 'L M A', 'Dr');
insert into ACADEMIC values (134, 103, 'Owen', 'Kenneth', 'K M', 'Dr');
insert into ACADEMIC values (135, 103, 'Carroll', 'Ulf', 'U K', 'Dr');
insert into ACADEMIC values (137, 105, 'Chalmers', 'Bijan', 'B D', 'Dr');
insert into ACADEMIC values (138, 105, 'Mayston', 'Brian', 'B A J', 'AProf');
insert into ACADEMIC values (139, 105, 'Marziani', 'Rolf', 'R K B', 'Dr');
insert into ACADEMIC values (140, 105, 'Wheeler', 'Ben', 'B K', 'Dr');
insert into ACADEMIC values (141, 105, 'Ashley', 'Maria', 'M J', 'Mr');
insert into ACADEMIC values (142, 105, 'Lawitzke', 'Ky', 'K R T', 'Dr');
insert into ACADEMIC values (143, 106, 'Stewart', 'Andrew', 'A D P', 'Dr');
insert into ACADEMIC values (144, 106, 'Kinsella', 'Declan', 'D G G', 'Prof');
insert into ACADEMIC values (145, 106, 'Prakash', 'Kate', 'K H', 'Dr');
insert into ACADEMIC values (146, 107, 'Marcy', 'Ike', 'I H', 'Ms');
insert into ACADEMIC values (147, 108, 'Witt', 'Brian', 'B P G', 'Mr');
insert into ACADEMIC values (148, 108, 'Delavega', 'Demetrios', 'D P', 'Mr');
insert into ACADEMIC values (149, 108, 'Cunningham', 'Tim', 'T T', 'Mr');
insert into ACADEMIC values (150, 108, 'Steinhbel', 'Leeroy', 'L G D', 'Mr');
insert into ACADEMIC values (151, 108, 'Nielsen', 'Morgan', 'M S', 'Dr');
insert into ACADEMIC values (152, 108, 'Steiner', 'Oleg', 'O J K', 'Prof');
insert into ACADEMIC values (153, 108, 'Wallace', 'Valdis', 'V J W', 'Mr');
insert into ACADEMIC values (154, 108, 'Lai', 'Chris', 'C J', 'Dr');
insert into ACADEMIC values (155, 108, 'James', 'Frank', 'F X', 'Mr');
insert into ACADEMIC values (156, 108, 'Martin', 'Faried', 'F G', 'AProf');
insert into ACADEMIC values (157, 108, 'Conduit', 'Sunny', 'S P', 'Dr');
insert into ACADEMIC values (158, 108, 'Meier', 'Eric', 'E J', 'Dr');
insert into ACADEMIC values (159, 108, 'Bigelow', 'Hassan', 'H D', 'Mrs');
insert into ACADEMIC values (160, 108, 'Nguyen', 'Mark', 'M R', 'Mr');
insert into ACADEMIC values (161, 109, 'Pines', 'Tim', 'T R', 'Dr');
insert into ACADEMIC values (162, 110, 'Betts', 'Neil', 'N P', 'Dr');
insert into ACADEMIC values (163, 111, 'Peterson', 'Stefan', 'S G', 'Dr');
insert into ACADEMIC values (164, 111, 'Stanton', 'Ballintijn', 'B G W', 'Dr');
insert into ACADEMIC values (165, 111, 'Tope', 'Donn', 'D C', 'Dr');
insert into ACADEMIC values (166, 111, 'Buie', 'William', 'W R I', 'Dr');
insert into ACADEMIC values (167, 112, 'Bergquist', 'Benjamin', 'B M', 'Dr');
insert into ACADEMIC values (168, 113, 'Berg', 'Tony', 'T D', 'Mr');
insert into ACADEMIC values (169, 113, 'Roland', 'Trever', 'T C A', 'Dr');
insert into ACADEMIC values (170, 114, 'Numnonda', 'Paul', 'P N', 'Mr');
insert into ACADEMIC values (171, 114, 'Dube', 'Shaji', 'S P', 'AProf');
insert into ACADEMIC values (172, 114, 'Klein', 'Lei', 'L C', 'Dr');
insert into ACADEMIC values (173, 115, 'Kok', 'Sinan', 'S S', 'Mr');
insert into ACADEMIC values (174, 116, 'Decair', 'Cyrus', 'C D', 'Dr');
insert into ACADEMIC values (175, 116, 'Williams', 'Thomas', 'T J', 'Dr');
insert into ACADEMIC values (176, 116, 'Anderson', 'Spenser', 'S G', 'Dr');
insert into ACADEMIC values (177, 116, 'Glicksman', 'Roar', 'R I J', 'Dr');
insert into ACADEMIC values (178, 116, 'Empranthiri', 'Bill', 'B J', 'Dr');
insert into ACADEMIC values (179, 116, 'Hill', 'Dave', 'D D', 'Mr');
insert into ACADEMIC values (180, 116, 'Wong', 'Andrew', 'A P A', 'Dr');
insert into ACADEMIC values (181, 116, 'Steyn', 'Michaael', 'M A', 'Prof');
insert into ACADEMIC values (182, 116, 'Robert', 'Daniel', 'D M E', 'Prof');
insert into ACADEMIC values (183, 116, 'Shannon', 'Koh', 'K H', 'Dr');
insert into ACADEMIC values (184, 116, 'Scanlon', 'Randolph', 'R P J', 'Dr');
insert into ACADEMIC values (185, 116, 'Tamaccio', 'Robert', 'R G', 'Prof');
insert into ACADEMIC values (186, 116, 'Conner', 'Eric', 'E E', 'Mr');
insert into ACADEMIC values (187, 116, 'Mir', 'Larry', 'L G', 'Mr');
insert into ACADEMIC values (188, 116, 'Saettler', 'Sandland', 'S J', 'Prof');
insert into ACADEMIC values (189, 116, 'Korman', 'Robert', 'R J', 'Dr');
insert into ACADEMIC values (190, 119, 'Morse', 'Frank', 'F J', 'Prof');
insert into ACADEMIC values (191, 119, 'Bierling', 'Ken', 'K R E', 'Mr');
insert into ACADEMIC values (192, 119, 'Ganguly', 'Ingo', 'I D R', 'Mr');
insert into ACADEMIC values (193, 119, 'McAleer', 'David', 'D J G', null);
insert into ACADEMIC values (194, 119, 'Hahm', 'Deepak', 'D J F', 'Dr');
insert into ACADEMIC values (195, 119, 'Hall', 'Dhr', 'D C F', 'Dr');
insert into ACADEMIC values (196, 119, 'Hlynka', 'Jack', 'J M W', 'Dr');
insert into ACADEMIC values (197, 120, 'Chiou', 'John', 'J A H J', 'Prof');
insert into ACADEMIC values (198, 121, 'Chen', 'Cheryl', 'C JS', 'Dr');
insert into ACADEMIC values (199, 122, 'Karr', 'Svante', 'S K', 'Mr');
insert into ACADEMIC values (200, 122, 'Hedges', 'Thomas', 'T J K', 'Prof');
insert into ACADEMIC values (201, 122, 'Kellner', 'Hans', 'H J', 'Mrs');
insert into ACADEMIC values (202, 122, 'Kilg', 'Adam', 'A T', 'AProf');
insert into ACADEMIC values (203, 122, 'Mitchell', 'Iain', 'I B', 'Dr');
insert into ACADEMIC values (204, 122, 'Schaeffer', 'Rob', 'R C B', 'Dr');
insert into ACADEMIC values (205, 122, 'Zakel', 'Will', 'W B', 'Mr');
insert into ACADEMIC values (206, 122, 'Robinson', 'Edward', 'E R', 'Dr');
insert into ACADEMIC values (207, 122, 'Zinn', 'Kevin', 'K J', 'Mr');
insert into ACADEMIC values (208, 122, 'Ray', 'Eric', 'E D', 'Mr');
insert into ACADEMIC values (209, 123, 'Boy', 'John', 'J G', 'Mr');
insert into ACADEMIC values (212, 122, 'Henri', 'Bob', 'B T R', 'Dr');
insert into ACADEMIC values (213, 102, 'Eek', 'Jorge', 'J K', null);
insert into ACADEMIC values (214, 124, 'Mackiewicz', 'Nathan', 'N G', 'AProf');
insert into ACADEMIC values (215, 124, 'Berends', 'Geoffrey', 'G G I', 'Mr');
insert into ACADEMIC values (216, 124, 'Gerritsen', 'Luigi', 'L P D', 'Dr');
insert into ACADEMIC values (217, 124, 'Winter', 'Elisabeth', 'E B H', 'Mr');
insert into ACADEMIC values (218, 124, 'Nieberger', 'Brad', 'B P D', 'Mr');
insert into ACADEMIC values (219, 124, 'Leonida', 'Dominik', 'D D L', 'Dr');
insert into ACADEMIC values (220, 124, 'Minker', 'David', 'D G R', 'Mr');
insert into ACADEMIC values (221, 124, 'Baruffi', 'Heikki', 'H D H', 'Mr');
insert into ACADEMIC values (222, 122, 'Ringer', 'Heinz', 'H R', 'Mr');
insert into ACADEMIC values (223, 106, 'Osburn', 'Aldis', 'A G R', 'Dr');
insert into ACADEMIC values (224, 110, 'Page', 'Jim', 'J A N', 'Dr');
insert into ACADEMIC values (225, 106, 'Beattie', 'Roger', 'R S', 'Dr');
insert into ACADEMIC values (226, 123, 'Pant', 'Jack', 'J M', 'Dr');
insert into ACADEMIC values (227, 103, 'Friedman', 'James', 'J C N G', 'AProf');
insert into ACADEMIC values (228, 122, 'Miller', 'Gail', 'G C W', 'Mr');
insert into ACADEMIC values (229, 122, 'Glazer', 'Bernd', 'B U', 'Mr');
insert into ACADEMIC values (230, 122, 'Burgeson', 'Jason', 'J B', 'Prof');
insert into ACADEMIC values (231, 122, 'Howard', 'George', 'G J', 'AProf');
insert into ACADEMIC values (232, 115, 'Grohol', 'Pete', 'P P', 'Prof');
insert into ACADEMIC values (233, 115, 'Goudie', 'Daniel', 'D B', 'Dr');
insert into ACADEMIC values (234, 115, 'Horne', 'Susan', 'S R F', 'Dr');
insert into ACADEMIC values (235, 115, 'Weinstock', 'Maria', 'M H', 'Dr');
insert into ACADEMIC values (236, 115, 'Smith', 'Mark', 'M M R', 'Dr');
insert into ACADEMIC values (237, 115, 'Link', 'Andre', 'A M', 'Dr');
insert into ACADEMIC values (238, 115, 'Muthukumar', 'Corey', 'C D M', 'Mr');
insert into ACADEMIC values (239, 115, 'Christofanelli', 'Dean', 'D C', 'Dr');
insert into ACADEMIC values (240, 115, 'McHenry', 'Frederick', 'F M', 'Dr');
insert into ACADEMIC values (241, 115, 'Powers', 'John', 'J K', 'Mr');
insert into ACADEMIC values (242, 115, 'Herrera', 'Daniel', 'D G', 'Dr');
insert into ACADEMIC values (243, 110, 'Tait', 'Clifford', 'C E V', 'Prof');
insert into ACADEMIC values (244, 110, 'Frank', 'Cesar', 'C B B', 'Dr');
insert into ACADEMIC values (245, 110, 'Aigner', 'Tony', 'T R P', 'Prof');
insert into ACADEMIC values (246, 110, 'Berggreen', 'Shivanand', 'S I', 'Dr');
insert into ACADEMIC values (247, 110, 'Tanji', 'Lucheng', 'L J B', 'Dr');
insert into ACADEMIC values (248, 120, 'Orth', 'Tino', 'T P', 'Mr');
insert into ACADEMIC values (249, 112, 'McKelvey', 'Paul', 'P P J', 'Mr');
insert into ACADEMIC values (250, 118, 'Lewine', 'Robert', 'R J', 'Mr');
insert into ACADEMIC values (251, 100, 'Woodpecker', 'Omar', 'O C P', 'Dr');
insert into ACADEMIC values (252, 108, 'Spota', 'Derek', 'D G', 'Mr');
insert into ACADEMIC values (253, 116, 'Sinha', 'Doug', 'D J', 'Prof');
insert into ACADEMIC values (254, 122, 'Briggs', 'Alexander', 'A J', 'Mr');
insert into ACADEMIC values (255, 108, 'Trenholme', 'Jamie', 'J J M', 'Mr');
insert into ACADEMIC values (256, 122, 'Richer', 'Hans', 'H S K', 'Mr');
insert into ACADEMIC values (257, 100, 'Gladius', 'Bill', 'B R', 'Dr');
insert into ACADEMIC values (258, 108, 'Murdock', 'Mucho', 'M H L', 'Dr');
insert into ACADEMIC values (259, 100, 'Bialecki', 'Stephenson', 'S L A', 'Dr');
insert into ACADEMIC values (260, 111, 'White', 'Roger', 'R C S', 'Prof');
insert into ACADEMIC values (261, 111, 'Riggins', 'Ronnie', 'R E J', 'Dr');
insert into ACADEMIC values (262, 111, 'Ooi', 'Scott', 'S C', 'Cmdr');
insert into ACADEMIC values (263, 111, 'Maclean', 'Clark', 'C D', 'Mr');
insert into ACADEMIC values (264, 111, 'Harding', 'Eduardo', 'E L P', 'Dr');
insert into ACADEMIC values (265, 111, 'Mahdavi', 'Tim', 'T D L', 'Mr');
insert into ACADEMIC values (266, 111, 'Taguchi', 'Mikki', 'M R A', 'Dr');
insert into ACADEMIC values (267, 111, 'Schwenk', 'Mohand', 'M C S J', 'Mr');
insert into ACADEMIC values (268, 111, 'Mikusko', 'Keith', 'K D', 'Mr');
insert into ACADEMIC values (269, 111, 'McCauley', 'Simon', 'S J', 'Ms');
insert into ACADEMIC values (271, 111, 'Picard', 'Doug', 'D F', 'Dr');
insert into ACADEMIC values (272, 111, 'Brian', 'Jason', 'J D B', 'Mr');
insert into ACADEMIC values (273, 111, 'Bredfeldt', 'Floeckner', 'F J M', 'Mrs');
insert into ACADEMIC values (274, 125, 'Taur', 'Ryszard', 'R T Y', 'Dr');
insert into ACADEMIC values (275, 125, 'Federkins', 'Kevin', 'K P', 'Dr');
insert into ACADEMIC values (276, 125, 'Lucas', 'Gary', 'G A', 'Dr');
insert into ACADEMIC values (277, 125, 'Fitzgerald', 'Glenn', 'G G', 'Dr');
insert into ACADEMIC values (278, 125, 'Bell', 'Jason', 'J G', 'Mr');
insert into ACADEMIC values (279, 125, 'Prior', 'Lori', 'L R P', 'Dr');
insert into ACADEMIC values (280, 125, 'Grantham', 'Jerry', 'J L J', 'Dr');
insert into ACADEMIC values (281, 125, 'Shetty', 'Gerard', 'G D B', 'Dr');
insert into ACADEMIC values (282, 125, 'Khadye', 'Roger', 'R L J', 'Dr');
insert into ACADEMIC values (283, 125, 'Palmer', 'Dennis', 'D R', 'Prof');
insert into ACADEMIC values (284, 125, 'Bruce', 'Steve', 'S Z', 'Dr');
insert into ACADEMIC values (285, 125, 'Cessaro', 'Don', 'D A', 'Dr');
insert into ACADEMIC values (286, 125, 'Makki', 'Adam', 'A L', 'Dr');
insert into ACADEMIC values (287, 125, 'Hinojosa', 'James', 'J T', 'Dr');
insert into ACADEMIC values (288, 125, 'Rooney', 'Xuming', 'X Z', 'Dr');
insert into ACADEMIC values (289, 125, 'Selby', 'Phil', 'P H', 'Dr');
insert into ACADEMIC values (290, 125, 'Garber', 'Jonathan', 'J E A', 'AProf');
insert into ACADEMIC values (291, 125, 'Aristotle', 'David', 'D L', 'Dr');
insert into ACADEMIC values (292, 125, 'Langstaff', 'Alan', 'A P J', 'Dr');
insert into ACADEMIC values (293, 125, 'Duvall', 'Chad', 'C P G', 'AProf');
insert into ACADEMIC values (294, 125, 'Weikamp', 'Mark', 'M J', 'Mr');
insert into ACADEMIC values (295, 126, 'Das', 'Ron', 'R J', 'Dr');
insert into ACADEMIC values (296, 126, 'Jacobs', 'Tess', 'T G', 'Mr');
insert into ACADEMIC values (297, 119, 'Roy', 'Tzach', 'T B H', 'Mr');
insert into ACADEMIC values (298, 127, 'Santhanakrishnan', 'Alan', 'A G J', 'Dr');
insert into ACADEMIC values (299, 119, 'Marquis', 'Thomas', 'T B S', 'Mr');
insert into ACADEMIC values (300, 119, 'Koska', 'Joachim', 'J M J P', 'Mr');
insert into ACADEMIC values (301, 119, 'Howell', 'Matthew', 'M J H', 'Ms');
insert into ACADEMIC values (302, 119, 'Brueck', 'Palyne', 'P G J', 'Prof');
insert into ACADEMIC values (303, 119, 'Otte', 'Albyn', 'A M M', 'Ms');
insert into ACADEMIC values (304, 119, 'Gass', 'Mark', 'M A J', 'Dr');
insert into ACADEMIC values (305, 119, 'Whitman', 'Helmuth', 'H S P', 'Ms');
insert into ACADEMIC values (306, 119, 'Jabbar', 'Murali', 'M J R', 'Dr');
insert into ACADEMIC values (307, 119, 'Duchowski', 'Anders', 'A P J', 'Ms');
insert into ACADEMIC values (308, 119, 'Portz', 'Shawn', 'S J J', 'Dr');
insert into ACADEMIC values (309, 116, 'Maples', 'Rich', 'R W P', 'Dr');
insert into ACADEMIC values (310, 128, 'Kuhn', 'Paul', 'P J R', 'Prof');
insert into ACADEMIC values (311, 128, 'Singh', 'Balarie', 'B N', 'Dr');
insert into ACADEMIC values (312, 128, 'Perry', 'Louis', 'L R J', 'AProf');
insert into ACADEMIC values (313, 128, 'LeSable', 'Kwok', 'K J', 'Prof');
insert into ACADEMIC values (314, 128, 'Turnbull', 'Janis', 'J J H', 'Dr');
insert into ACADEMIC values (315, 147, 'Kalander', 'Kasper', 'K A C', 'Dr');
insert into ACADEMIC values (316, 128, 'Matthews', 'Stephen', 'S A D', 'Dr');
insert into ACADEMIC values (317, 116, 'Hartkoorn', 'Scott', 'S P A', 'Prof');
insert into ACADEMIC values (319, 106, 'MacMillan', 'Michael', 'M V', 'Ms');
insert into ACADEMIC values (320, 120, 'Szymanski', 'Neil', 'N C A', 'Dr');
insert into ACADEMIC values (321, 128, 'Read', 'Jeremy', 'J M J', 'Dr');
insert into ACADEMIC values (322, 128, 'Howard', 'Jamie', 'J N Y', 'AProf');
insert into ACADEMIC values (323, 106, 'Blavatnik', 'Doug', 'D S L', 'Dr');
insert into ACADEMIC values (324, 128, 'Hohenstein', 'Kel', 'K W R', 'Dr');
insert into ACADEMIC values (325, 127, 'Banker', 'Pisharody', 'P P J', 'Dr');
insert into ACADEMIC values (326, 116, 'Beegle', 'Tim', 'T R G', 'Mr');
insert into ACADEMIC values (327, 128, 'Koren', 'Joseph', 'J J', 'Ms');
insert into ACADEMIC values (328, 118, 'Mikulcik', 'Neal', 'N P R', 'Dr');
insert into ACADEMIC values (329, 130, 'Findlow', 'Jim', 'J K', 'Dr');
insert into ACADEMIC values (330, 140, 'Bob', 'Michael', 'M A', 'Mr');
insert into ACADEMIC values (331, 132, 'Wood', 'Eric', 'E R', 'Dr');
insert into ACADEMIC values (332, 133, 'Eaves', 'Maureen', 'M D H', 'Dr');
insert into ACADEMIC values (333, 116, 'Vaughan', 'Greg', 'G A', 'Mr');
insert into ACADEMIC values (334, 133, 'Hedrick', 'Alison', 'A T M', 'Prof');
insert into ACADEMIC values (335, 133, 'Ebbert', 'Abigail', 'A J', null);
insert into ACADEMIC values (336, 134, 'Baindur', 'Andy', 'A M', 'Mr');
insert into ACADEMIC values (337, 133, 'Jewell', 'Joseph', 'J G B', null);
insert into ACADEMIC values (338, 133, 'Neil', 'Paul', 'P S S', 'Dr');
insert into ACADEMIC values (339, 133, 'Bonin', 'Jose', 'J M J', null);
insert into ACADEMIC values (340, 128, 'Reingold', 'Brent', 'B D D', 'Dr');
insert into ACADEMIC values (341, 135, 'Shebs', 'Chen', 'C J R', 'Dr');
insert into ACADEMIC values (342, 135, 'Thurston', 'Dan', 'D S', 'Mr');
insert into ACADEMIC values (343, 135, 'Craig', 'Marc', 'M M J J', 'Ms');
insert into ACADEMIC values (344, 135, 'Hochstaettler', 'Daniel', 'D C', null);
insert into ACADEMIC values (345, 114, 'Mak', 'Diana', 'D G', 'Dr');
insert into ACADEMIC values (346, 103, 'Paterson', 'Brad', 'B A M', 'Dr');
insert into ACADEMIC values (347, 146, 'Tran', 'Melissa', 'M S', 'Dr');
insert into ACADEMIC values (348, 135, 'McMahon', 'Albert', 'A R H', 'Mr');
insert into ACADEMIC values (349, 135, 'Kaufman', 'Darrell', 'D M P', 'Ms');
insert into ACADEMIC values (350, 132, 'Shin', 'Michael', 'M M J', 'AProf');
insert into ACADEMIC values (351, 136, 'Massey', 'Randy', 'R R', 'Dr');
insert into ACADEMIC values (352, 114, 'Palmeri', 'Anna', 'A D', 'Dr');
insert into ACADEMIC values (353, 101, 'Nodine', 'Peter', 'P N', 'Dr');
insert into ACADEMIC values (354, 100, 'Panvalkar', 'Daniel', 'D R A', 'Mr');
insert into ACADEMIC values (355, 118, 'McCune', 'Robert', 'R C', 'Mr');
insert into ACADEMIC values (356, 118, 'Sacco', 'Vik', 'V N W', 'Dr');
insert into ACADEMIC values (357, 118, 'Degrassi', 'Luis', 'L R G', 'Mr');
insert into ACADEMIC values (358, 118, 'Prigge', 'Lydia', 'L S', 'Mr');
insert into ACADEMIC values (359, 118, 'Edelson', 'Bryan', 'B P D', 'Mr');
insert into ACADEMIC values (360, 118, 'Ly', 'Pierre', 'P M P', 'Dr');
insert into ACADEMIC values (361, 118, 'Brooke', 'Andrew', 'A C D', 'Prof');
insert into ACADEMIC values (363, 118, 'Evans', 'Gerard', 'G D M W', 'AProf');
insert into ACADEMIC values (364, 118, 'Benner', 'Raghavan', 'R G H B', 'Mr');
insert into ACADEMIC values (365, 118, 'Potter', 'Madam', 'M T E', 'Dr');
insert into ACADEMIC values (366, 118, 'Brooks', 'Yvon', 'Y J L', 'Ms');
insert into ACADEMIC values (367, 118, 'MacIntyre', 'Stephen', 'S K E', 'Miss');
insert into ACADEMIC values (368, 100, 'Kwon', 'Ron', 'R R M', 'Prof');
insert into ACADEMIC values (369, 100, 'Lawson', 'Robert', 'R C', 'Dr');
insert into ACADEMIC values (370, 137, 'Pierce', 'Matthew', 'M C N', 'Dr');
insert into ACADEMIC values (371, 123, 'Dahlberg', 'Gert', 'G P H', 'Mr');
insert into ACADEMIC values (372, 112, 'Rivoire', 'Tayfun', 'T S', 'Dr');
insert into ACADEMIC values (373, 133, 'Haag', 'Michael', 'M A E', null);
insert into ACADEMIC values (374, 138, 'Pitard', 'Enhua', 'E P F', 'Dr');
insert into ACADEMIC values (375, 138, 'Joe', 'Steven', 'S M S', 'Dr');
insert into ACADEMIC values (376, 138, 'Smith', 'Christian', 'C R L', 'Dr');
insert into ACADEMIC values (377, 138, 'Waite', 'Dan', 'D C J', 'Mr');
insert into ACADEMIC values (378, 133, 'Lee', 'Lee', 'L D', null);
insert into ACADEMIC values (379, 133, 'Albert', 'Diane', 'D R', null);
insert into ACADEMIC values (380, 133, 'Niguma', 'Sarah', 'S P', null);
insert into ACADEMIC values (381, 133, 'Coulter', 'Tony', 'T J', null);
insert into ACADEMIC values (382, 133, 'Kelley', 'Larry', 'L M', null);
insert into ACADEMIC values (383, 133, 'Ahern', 'Eric', 'E S', null);
insert into ACADEMIC values (384, 133, 'McCuen', 'Giuseppe', 'G G', null);
insert into ACADEMIC values (385, 133, 'Allis', 'Gokhan', 'G Z', null);
insert into ACADEMIC values (386, 133, 'Berggren', 'Jim', 'J D', null);
insert into ACADEMIC values (387, 133, 'Wooten', 'Bruce', 'B M', null);
insert into ACADEMIC values (388, 133, 'Henry', 'Pascal', 'P D', null);
insert into ACADEMIC values (389, 133, 'Yum', 'Dave', 'D B', null);
insert into ACADEMIC values (390, 133, 'Zylstra', 'Timothy', 'T C', null);
insert into ACADEMIC values (391, 138, 'Ruiz', 'Larry', 'L P D', 'Mr');
insert into ACADEMIC values (392, 138, 'Benjamin', 'Steve', 'S R A', 'AProf');
insert into ACADEMIC values (393, 138, 'Sun', 'James', 'J N', 'Dr');
insert into ACADEMIC values (394, 136, 'Ditlefsen', 'Sanjay', 'S M', 'Ms');
insert into ACADEMIC values (395, 123, 'Heine', 'Kevin', 'K M', 'Mr');
insert into ACADEMIC values (396, 138, 'Sheehan', 'Ahson', 'A C', 'Dr');
insert into ACADEMIC values (397, 104, 'Debenedetti', 'Simon', 'S R J', 'Prof');
insert into ACADEMIC values (399, 139, 'Coan', 'Larry', 'L A J', 'Prof');
insert into ACADEMIC values (400, 137, 'David', 'Chris', 'C T', 'Mr');
insert into ACADEMIC values (401, 119, 'Olnaes', 'Joe', 'J G', 'Mr');
insert into ACADEMIC values (402, 116, 'Schmid', 'Joseph', 'J P', 'Dr');
insert into ACADEMIC values (403, 138, 'Bartzsch', 'David', 'D R C', 'Dr');
insert into ACADEMIC values (404, 116, 'Pennypacker', 'William', 'W M', 'Dr');
insert into ACADEMIC values (405, 123, 'Zhu', 'Daniel', 'D J A', 'Dr');
insert into ACADEMIC values (406, 123, 'Ferkovich', 'Dongyu', 'D J R', 'Mr');
insert into ACADEMIC values (407, 123, 'Coates', 'Ian', 'I M', 'Ms');
insert into ACADEMIC values (408, 123, 'Friedrichs', 'David', 'D G K', 'Mr');
insert into ACADEMIC values (409, 139, 'Eddins', 'Harald', 'H M A', 'Mr');
insert into ACADEMIC values (410, 126, 'Knight', 'Ray', 'R G', 'Mr');
insert into ACADEMIC values (411, 112, 'Plainguet', 'Ryan', 'R A L', 'Dr');
insert into ACADEMIC values (413, 103, 'Kesek', 'Gerald', 'G L G C', 'Dr');
insert into ACADEMIC values (414, 127, 'Platt', 'Edward', 'E D J', 'Dr');
insert into ACADEMIC values (415, 137, 'Mahadevan', 'Thomas', 'T J S', 'Dr');
insert into ACADEMIC values (416, 109, 'Andrews', 'Ganesh', 'G P A', 'AProf');
insert into ACADEMIC values (417, 120, 'Chan', 'Alberto', 'A C N', 'Dr');
insert into ACADEMIC values (418, 120, 'Hardie', 'Ronnie', 'R C D', 'Dr');
insert into ACADEMIC values (419, 120, 'Pasquale', 'Kris', 'K A S', 'Dr');
insert into ACADEMIC values (420, 113, 'Drake', 'Steven', 'S J D', 'Dr');
insert into ACADEMIC values (421, 113, 'Kelly', 'John', 'J R', null);
insert into ACADEMIC values (422, 109, 'Carpenter', 'Lanetta', 'L S', 'Dr');
insert into ACADEMIC values (423, 109, 'Benna', 'Fuzzy', 'F Y K', 'Dr');
insert into ACADEMIC values (424, 109, 'Fleming', 'Craig', 'C R K', 'Dr');
insert into ACADEMIC values (425, 120, 'Larsen', 'Ray', 'R J', 'Dr');
insert into ACADEMIC values (426, 120, 'Woo', 'Paolo', 'P V M', null);
insert into ACADEMIC values (427, 113, 'Genyus', 'Henry', 'H T L', 'Dr');
insert into ACADEMIC values (428, 113, 'Pinto', 'Larry', 'L L', 'Ms');
insert into ACADEMIC values (429, 112, 'Leroy', 'Vivian', 'V P W', 'Dr');
insert into ACADEMIC values (430, 113, 'Brock', 'Tim', 'T V T', 'Dr');
insert into ACADEMIC values (431, 139, 'Drexler', 'Simon', 'S Y', 'Dr');
insert into ACADEMIC values (432, 109, 'Enoksson', 'Alan', 'A Y A', 'Mr');
insert into ACADEMIC values (433, 126, 'Grav', 'Gerald', 'G G', 'Dr');
insert into ACADEMIC values (434, 103, 'Rodriguez', 'Larry', 'L G T', 'AProf');
insert into ACADEMIC values (435, 104, 'Longcore', 'Joel', 'J G M', 'Dr');
insert into ACADEMIC values (436, 103, 'Scott', 'Bob', 'B I', 'Dr');
insert into ACADEMIC values (437, 103, 'Wood', 'Nathan', 'N R L', 'Mrs');
insert into ACADEMIC values (438, 103, 'Reagan', 'David', 'D P', 'Dr');
insert into ACADEMIC values (439, 136, 'Finin', 'Peter', 'P', 'Mr');
insert into ACADEMIC values (440, 103, 'Alloy', 'Neil', 'N F.', null);
insert into ACADEMIC values (441, 139, 'Gefaell', 'Swami', 'S R G.', 'Dr');
insert into ACADEMIC values (442, 137, 'Allan', 'Kevin', 'K G', 'Dr');
insert into ACADEMIC values (443, 102, 'Mertalo', 'Sean', 'S B C', 'Dr');
insert into ACADEMIC values (444, 141, 'Havey', 'Sarah', 'S D A', 'Dr.');
insert into ACADEMIC values (446, 108, 'Padilla', 'Bill', 'B C.A.', 'AProf');
insert into ACADEMIC values (447, 122, 'Denley', 'Rich', 'R R', 'Dr');
insert into ACADEMIC values (448, 128, 'Boniface', 'Michael', 'M A', 'Dr');
insert into ACADEMIC values (449, 126, 'Moon', 'Roberto', 'R R', 'Dr');
insert into ACADEMIC values (450, 128, 'Koniaris', 'Eric', 'E D.B.', 'Dr');
insert into ACADEMIC values (451, 126, 'Preece', 'Gilles', 'G M.V.', 'Dr');
insert into ACADEMIC values (452, 112, 'Osborn', 'Saptho', 'S B', 'Dr');
insert into ACADEMIC values (453, 147, 'Nappi', 'Richard', 'R C', 'Dr');
insert into ACADEMIC values (454, 126, 'Frost', 'Tom', 'T V', 'Dr');
insert into ACADEMIC values (455, 125, 'Thornton', 'Mustafa', 'M LS', null);
insert into ACADEMIC values (456, 126, 'Roebuck', 'George', 'G J.A.', 'Dr.');
insert into ACADEMIC values (457, 119, 'Tong', 'Daryl', 'D C.A.', 'Dr.');
insert into ACADEMIC values (458, 105, 'White', 'Purple', 'P JN', 'Prof.');
insert into ACADEMIC values (459, 146, 'Woodward', 'Willem', 'W P S', 'Dr');
insert into ACADEMIC values (460, 114, 'Grenald', 'Batel', 'B W J', 'Dr');
insert into ACADEMIC values (461, 100, 'Lesiak', 'Charles', 'C P', 'Dr.');
insert into ACADEMIC values (462, 137, 'Wellen', 'Randall', 'R P', 'Dr.');
insert into ACADEMIC values (463, 103, 'Spearing', 'James', 'J B', 'Dr.');
insert into ACADEMIC values (464, 147, 'Prior', 'George', 'G D', 'Dr.');
insert into ACADEMIC values (465, 100, 'Dodge', 'Noah', 'N MJ', 'AProf');
insert into ACADEMIC values (466, 144, 'Stauffer', 'Roger', 'R P.A.', 'Mr');
insert into ACADEMIC values (467, 144, 'Owens', 'Brian', 'B T A', 'Ms');
insert into ACADEMIC values (468, 144, 'Gortatowsky', 'Michael', 'M P K', 'Mr');
insert into ACADEMIC values (469, 103, 'Wooldridge', 'Shaq', 'S T.', 'Dr.');