insert into DEPARTMENT values (100, 'GU CIT', 'Griffith University', 'School of Computing and Information Technology', 'Qld', 4111);
insert into DEPARTMENT values (101, 'JCU CS', 'James Cook University of North Queensland', 'Computer Science', 'Qld', 4811);
insert into DEPARTMENT values (102, 'LTU CSCE', 'La Trobe University', 'Computer Science and Computer Engineering', 'VIC', 3083);
insert into DEPARTMENT values (103, 'MQU MPCE', 'Macquarie University', 'Computing', 'NSW', 2109);
insert into DEPARTMENT values (104, 'MQU RCASE', 'Macquarie University', 'JRCASE', 'NSW', 2109);
insert into DEPARTMENT values (105, 'MNU CS', 'Monash University (Clayton)', 'Computer Science', 'VIC', 3168);
insert into DEPARTMENT values (106, 'MRU CS', 'Murdoch University', 'Computer Science', 'WA', 6150);
insert into DEPARTMENT values (107, 'NUS ISCS', 'National University of Singapore', 'Information Systems and Computer Science', '', 0);
insert into DEPARTMENT values (108, 'QUT CS', 'Queensland University of Technology', 'Computing Science', 'QLD', 4000);
insert into DEPARTMENT values (109, 'SUT IT', 'Swinburne University of Technology', 'School of Information Technology', 'VIC', 3122);
insert into DEPARTMENT values (110, 'ANU CSL', 'Australian National University', 'Computer Science Laboratory', 'ACT', 0200);
insert into DEPARTMENT values (111, 'ADFA CS', 'University College - ADFA - UNSW', 'Computer Science', 'ACT', 2600);
insert into DEPARTMENT values (112, 'UA CS', 'University of Adelaide', 'Computer Science', 'SA', 5005);
insert into DEPARTMENT values (113, 'UC ISE', 'University of Canberra', 'Information Sciences and Engineering', 'ACT', 2616);
insert into DEPARTMENT values (114, 'UNE MSCS', 'University of New England', 'Mathematics - Statistics and Computing Science', 'NSW', 2351);
insert into DEPARTMENT values (115, 'UNC CS', 'University of Newcastle', 'Computer Science', 'NSW', 2308);
insert into DEPARTMENT values (116, 'UQ IT', 'University of Queensland', 'School of Information Technology', 'Qld', 4072);
insert into DEPARTMENT values (118, 'FU CS', 'Flinders University', 'Department of Computer Science', 'SA', 5001);
insert into DEPARTMENT values (119, 'USA CIS', 'University of South Australia', 'School of Computer and Information Science', 'SA', 5095);
insert into DEPARTMENT values (120, 'UTH CS', 'University of Tasmania - Hobart', 'Department of Computer Science', 'TAS', 7001);
insert into DEPARTMENT values (121, 'UTL ACM', 'University of Tasmania at Launceston', 'Applied Computing and Mathematics', 'Tas', 7250);
insert into DEPARTMENT values (122, 'UTS CS', 'University of Technology - Sydney', 'School of Computing Sciences', 'NSW', 2007);
insert into DEPARTMENT values (123, 'UWSN DC', 'University of Western Sydney - Nepean', 'Department of Computing', 'NSW', 2747);
insert into DEPARTMENT values (124, 'UB MC', 'University of Ballarat', 'School of Mathematics and Computing', 'VIC', 3353);
insert into DEPARTMENT values (125, 'UM CS', 'University of Melbourne', 'Computer Science', 'VIC', 3052);
insert into DEPARTMENT values (126, 'RMIT CS', 'Royal Melbourne Institute of Technology', 'Computer Science', 'VIC', 3001);
insert into DEPARTMENT values (127, 'CSIRO DIT', 'Commonwealth Scientific and Industrial Research Org', 'Division of Information Technology', 'ACT', 2601);
insert into DEPARTMENT values (128, 'SU CS', 'University of Sydney', 'Basser Department of Computer Science', 'NSW', 2006);
insert into DEPARTMENT values (129, 'DSTO ITD', 'Defence Science and Technology Organisation', 'Information Technology Division', null, 0);
insert into DEPARTMENT values (130, 'UQ CITR', 'University of Queensland', 'Centre for Information Technology Research', 'Qld', 4072);
insert into DEPARTMENT values (131, 'UQ CRCDST', 'University of Queensland', 'CRC for Distributed Systems Technology', 'Qld', 4072);
insert into DEPARTMENT values (132, 'BU IT', 'Bond University', 'School of Information Technology', 'Qld', 4229);
insert into DEPARTMENT values (133, 'CUT CS', 'Curtin University of Technology', 'Computer Science', 'WA', 6001);
insert into DEPARTMENT values (134, 'QUT ISRC', 'Queensland University of Technology', 'Information Security Research Centre', 'Qld', 4001);
insert into DEPARTMENT values (135, 'ECU CS', 'Edith Cowan University', 'Computer Science', 'WA', 6050);
insert into DEPARTMENT values (136, 'MIAST NLP', 'Microsoft Institute of Adv Software Technology', 'NLP Research Unit', 'NSW', 2113);
insert into DEPARTMENT values (137, 'UNSW CSE', 'University of New South Wales', 'School of Computer Science and Engineering', 'NSW', 2052);
insert into DEPARTMENT values (138, 'UWA CS', 'University of Western Australia', 'Computer Science', 'WA', 6907);
insert into DEPARTMENT values (139, 'USQ MC', 'University of Southern Queensland', 'Department of Mathematics and Computing', 'Qld', 4350);
insert into DEPARTMENT values (140, 'QUT DSTC', 'Queensland University of Technology', 'CRC for Distributed Systems Technology', 'Qld', 4000);
insert into DEPARTMENT values (141, 'ANU CS', 'Australian National University', 'Department of Computer Science', 'ACT', 0200);
insert into DEPARTMENT values (142, 'UM DIS', 'University of Melbourne', 'Department of Information Systems', 'VIC', 3052);
insert into DEPARTMENT values (143, 'MNU GSCIT', 'Monash University', 'Gippsland School of Computing and I.T.', 'VIC', 3842);
insert into DEPARTMENT values (144, 'CQUMC', 'Central Queensland University', 'Department Mathematics and Computing', 'QLD', 4702);
insert into DEPARTMENT values (145, 'MNU SD', 'Monash University', 'Department of Software Development', 'VIC', 3145);
insert into DEPARTMENT values (146, 'VUT CS', 'Victoria University of Technology', 'Computer Science Department', 'VIC', 3088);
insert into DEPARTMENT values (147, 'NONE', 'No longer working in Australia', null, null, 0);
insert into DEPARTMENT values (148, 'UNKNOWN', 'Has moved. Old address no longer valid.', null, null, 0);